"""create payment & logistics tables, link tickets to user and order

Revision ID: e6dced6a10af
Revises: 2e6d701812e6
Create Date: 2026-09-05 22:20:25.920140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6dced6a10af'
down_revision: Union[str, Sequence[str], None] = '2e6d701812e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logistics',
    sa.Column('order_no', sa.String(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('order_no', 'step_no')
    )
    op.create_table('payments',
    sa.Column('order_no', sa.String(), nullable=False),
    sa.Column('pay_no', sa.String(), nullable=False),
    sa.Column('pay_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pay_time', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('order_no', 'pay_no')
    )
    with op.batch_alter_table('document_logs') as batch_op:
        batch_op.alter_column('message',
                   existing_type=sa.TEXT(),
                   nullable=False)
    op.add_column('tickets', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('order_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'order_no')
    op.drop_column('tickets', 'user_id')
    with op.batch_alter_table('document_logs') as batch_op:
        batch_op.alter_column('message',
                   existing_type=sa.TEXT(),
                   nullable=True)
    op.drop_table('payments')
    op.drop_table('logistics')
    # ### end Alembic commands ###
